pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        IMAGE_NAME = 'your-dockerhub-username/nginx:latest'
        EC2_HOST = 'ec2-user@<IP_PUBLICA_EC2>'
    }

    stages {
        stage('Checkout Código') {
            steps {
                git branch: 'main', url: 'https://github.com/sergioortiz17/devops-interview-solution.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Login en DockerHub') {
            steps {
                script {
                    sh "echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                script {
                    sh "docker push $IMAGE_NAME"
                }
            }
        }

        stage('Deploy en Servidor') {
            steps {
                sshagent (credentials: ['ec2-ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no $EC2_HOST <<EOF
                    docker pull $IMAGE_NAME
                    docker stop nginx-container || true
                    docker rm nginx-container || true
                    docker run -d --name nginx-container -p 80:80 $IMAGE_NAME
                    EOF
                    '''
                }
            }
        }
    }
}
