services:
  db:
    container_name: database
    image: postgres:12.0-alpine
    env_file: ./backend/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: django_backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: react_frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/

volumes:
  postgres_data:
  static:
  media:
